export enum ProductCategory {
  NORMAL_LAPTOP = 'normal_laptop',
  GAMING_LAPTOP = 'gaming_laptop',
  TABLET = 'tablet',
  NORMAL_DESKTOP_CPU = 'normal_desktop_cpu',
  GAMING_CPU = 'gaming_cpu',
  MONITORS = 'monitors',
  UPS = 'ups',
  IPG_PRODUCTS = 'ipg_products',
  ACCESSORIES = 'accessories',
  CCTV_DVR_NVR = 'cctv_dvr_nvr',
  CCTV_CAMERA = 'cctv_camera',
  SMPS = 'smps',
  OTHERS = 'others',
}
